version: "3.8"
services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    volumes:
      - mysql-vol:/app
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: short_url
      MYSQL_ROOT_HOST: '%'
volumes:
  mysql-vol:
    external: true